### ISSUE TITLE
Update SPEC 0 re: Python 3.11?

### ISSUE THREAD

**Issue by NickleDave** [scientific-python/specs#172]
Hi all,

Should the SPEC 0 doc be updated now that some core packages (numpy, scipy) have support for Python 3.11?  
Not quite clear to me as a downstream developer if I should be testing with Python 3.11, including it in pyproject.toml metadata as a supported Python, etc.

Opening an issue as @jarrodmillman stated should be done on the Discourse, e.g. like #141.
Sorry if there's some clear process around this I'm missing. Maybe a GitHub action could be set up to automatically update and that could be linked in the SPEC or something like that? (just to be clear about when it will change)

**Comment by bsipocz** [comment]
> Should the SPEC 0 doc be updated now that some core packages (numpy, scipy) have support for Python 3.11?

I would like to think the SPEC is about the underlying logic rather than the specific dates, aka we shouldn't need to constantly update it. 

> Not quite clear to me as a downstream developer if I should be testing with Python 3.11, including it in pyproject.toml metadata as a supported Python, etc

Yes, I think it's very much time. Maybe we need to update the language of the spec to encourage maintainers to include new versions in their CI as soon as possible (some libraries do test with beta release pythons, but lower downstream it is obviously difficult if not impossible if not all dependencies do this).

I start creating issues for the tools that should be there to support the specs.
