### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by tupui** [scientific-python/specs#240]
Was raised on the BOF session.

It could be good to encourage badges like this one:

```
![Static Badge](https://img.shields.io/badge/SPEC-0%2C1%2C4-brightgreen)
```

![Static Badge](https://img.shields.io/badge/SPEC-0%2C1%2C4-brightgreen)

(OC you can make this clickable so that it goes to the SPEC's website.)

**Comment by lagru** [comment]
I assume the numbers reference the endorsed SPECs? That list might get too long at some point. What do you think about providing two kinds of badges:
- A badge referencing a specific SPEC. And instead of a number we would encourage a short keyword, e.g. "SPEC | 0 - Minimum Version". Projects are free to add one or multiple ones.
- A summary badge, with a count of SPECs that a project aims to follow, e.g. "SPEC | 3 supported" or "SPEC | 3 adopted"

I am skeptical about displaying a count, because it might imply that more is better, even though projects might have good reasons not to adopt a SPEC. So the badge should definitely be an affirmative green always.

**Comment by tupui** [comment]
Yeah so I was thinking about just not showing any number at all too. It could just read SPEC|compliant. Or something like that.

**Comment by aterrel** [comment]
What determines if a discussion happens on github versus discourse?

**Comment by jarrodmillman** [comment]
And more meta stuff like this will likely happen in GH.

**Comment by tupui** [comment]
BTW, happy to see you here @aterrel 😃

**Comment by tupui** [comment]
Linked to that, or I can convert that comment into an issue.

On top of badges, what if we provided some sort of card?

I was looking at this (on Apple for an App you have these sorts of cards):
<img width="274" alt="Screenshot 2023-09-29 at 13 21 25" src="https://github.com/scientific-python/specs/assets/23188539/68f4eb72-e1d4-4cc8-b3aa-0fe1461293ad">

I imagine the same design but for SPECs. I am a bit lazy to do the mockup right now 😅, but replace the logo with our logo, instead of `Data ...` put the number of the SPEC and a short description. And then for the items bellow you write the implementation details. e.g. if you support SPEC 0 you say things like `Support x years` etc. You could either have such a card per SPEC, or just one cart which lists all endorsed SPECs with sections for all SPECs to give the implementation details.

**Comment by Carreau** [comment]
I think cards would make sens once we have a bit more specs in the pipeline.  +1 for badge. I think we could also suggest a github topic, so that it's easier to search for project using a spec.

**Comment by tupui** [comment]
Good idea for the GitHub topic +1

**Comment by bsipocz** [comment]
Re the badge in the opening: what about having one separate one for each SPECs rather than a joint? Then their link could point to the actual SPEC's page.

**Comment by bsipocz** [comment]
(and based on today's discussion, I suppose these badges should not mean "endorsed" but rather "implemented" or "follow" or whatever the right term will be. (maybe "SPEC 0 powered", though that's a bit too much I suppose )

**Comment by tupui** [comment]
Yeah not sure because that could quickly lead to Christmas trees in the readme. Projects like NetworkX already support a bunch so they would need to add multiple badges.

I think leaving this up to the projects is also ok. So we say: either make one badge per SPEC following *this* template, or have a single badge with *this other* template.

**Comment by bsipocz** [comment]
> they would need to add multiple badges.

I don't think the _need_ to add, but the could add the badges. 

My main motivation with the one per spec is that it could easily link back to, while the one above is a bit more misleading if the badge would look almost the same, just a different combination of numbers on it (which could then of course also lead to a Christmas tree appearance for projects that adopted a lot of them)

**Comment by Carreau** [comment]
I've added [`spec-0000`](https://github.com/topics/spec-0000) topic to IPython. We can add description to a topic only once there are enough repos with it.

**Comment by lagru** [comment]
> I think leaving this up to the projects is also ok. So we say: either make one badge per SPEC following this template, or have a single badge with this other template.

+1 on this. This fits with the philosophy of projects having agency with which SPECs they want to endorse. For the case were projects want to collect endorsed SPECs in a single badge, we could just offer two flavors: one that lists all endorsed ones, and one that just says something like "SPECs endorsed". 

Can we make it so that the badge has a white Scientific Python tree inside? That might make it more distinct and professional looking. :)

**Comment by jarrodmillman** [comment]
> I've added [`spec-0000`](https://github.com/topics/spec-0000) topic to IPython. We can add description to a topic only once there are enough repos with it.

Should it be `https://github.com/topics/spec-0` or `https://github.com/topics/SPEC-0` instead of `https://github.com/topics/spec-0000`? The `0000` was mainly just so things would sort properly when I use `ls` at the command-line in the spec repository on my laptop. Everywhere else we just refer to it as `SPEC 0`.

**Comment by jarrodmillman** [comment]
Since no one commented, I've taken it as tacit endorsement of `https://github.com/topics/spec-0000`. So I added the following topics to the [scientific-python/specs](https://github.com/scientific-python/spec) repo:

https://github.com/topics/spec-0000
https://github.com/topics/spec-0001
https://github.com/topics/spec-0004

**Comment by Carreau** [comment]
Should the above be edited, I think everything was changed to removed the leading zeroes.

And sorry I was (trying to). take time off until a few hours ago.
